// apps/solid/src/App.tsx
import { Component, createSignal } from "solid-js";
import { createList } from "./utils/list";
import logo from "./logo.svg";
import styles from "./App.module.css";

const App: Component = () => {
  const [list, setList] = createSignal(createList());

  setInterval(() => {
    setList(createList());
  }, 10);
  return (
    <div>
      <header class={styles.header}>
        <img src={logo} alt="" height="50" /> - Solid
      </header>
      <ul class={styles.App}>
        {list().map((item) => (
          <li>{item.name}</li>
        ))}
      </ul>
    </div>
  );
};

export default App;

// apps/react/src/App.tsx
import { useEffect, useState } from "react";
import reactLogo from "./assets/react.svg";
import "./App.css";
import { createList, token } from "./utils/list";
import { measureCallsPerSecond } from "./utils/logging";

function ListItem({ name }: { name: string }) {
  return <li>{name}</li>;
}

let intervals: number[] | null = null;

function App() {
  const [list, setList] = useState(createList());

  useEffect(() => {
    intervals =
      intervals ||
      list.map((item) =>
        setInterval(() => {
          measureCallsPerSecond("Interval");
          setList((list) => {
            measureCallsPerSecond("setListUnbuffered");
            return list.map((li) => {
              measureCallsPerSecond("listItemIteration");
              return item.id === li.id ? { id: li.id, name: token() } : li;
            });
          });
        }, 10)
      );

    return () => {
      intervals?.forEach((interval) => clearInterval(interval));
      intervals = null;
    };
  }, []);

  return (
    <>
      <div>
        <div className="logo">
          <img src={reactLogo} className="logo react" alt="React logo" />
          React
        </div>
        <ul>
          {list.map((item) => (
            <ListItem name={item.name} key={item.id} />
          ))}
        </ul>
      </div>
    </>
  );
}

export default App;
